stages:
  download:
    cmd: python source/download.py
    deps:
    - source/download.py
    params:
    - download.locs_id
    - download.year
    outs:
    - data/downloaded
  prepare:
    cmd: python source/prepare.py
    deps:
    - source/prepare.py
    params:
    - prepare.locs_id
    outs:
    - data/prepared/downloaded_data
    - data/prepared/downloaded_relevant_fields
  process:
    cmd: python source/process.py
    deps:
    - source/process.py
    params:
    - process.locs_id
    outs:
    - data/processed/downloaded_data_process
    - data/processed/downloaded_relevant_fields_process
